### PR TITLE
test remove expect test fail

### PR DESCRIPTION
**Pull request by craigsteffen**
Removes from test_might_fail from t/0700 script.  

### Description

This branch removes the test_might_fail from the last test of
t/0700-unifyfs-stage-full.t.  We will initially see if in the current
version of the sharness setup this is still needed.

If that works, we'll just submit this as is.  If not, we'll use
this branch to work out the problems, and then commit it when
it works.

This has not been tested; the PR being tested by
Travis IS the test.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by MichaelBrim** [comment]
@craigsteffen  I found another project that moved away from using test_cmp to using the cmp utility for comparison of binary files. I guess test_cmp is only valid for ascii text files - not sure if the files used by these unit tests are all text or not.

https://gitlab.cecs.anu.edu.au/comp8440/git/-/commit/b93e6e36637bed9d80f9ffa786ea78044fde6bac

**Comment by craigsteffen** [comment]
Ok, that's useful to know.

No, they're generated by dd-ing blocks of bytes out of /dev/rand (or
something; I don't remember the exact link).  The fact that copying the
files into Unify and then back out makes it not match in Travis but it
(normally) works on real systems is still very weird.

Thanks.  I'll get on summit and try to synch up with Jenna in the next
couple of days.

Craig

**Comment by MichaelBrim** [comment]
Closing this as it seems to be fixed in my client API PR

**Comment by CamStan** [comment]
@MichaelBrim, it appears the `test_might_fail` command is still in your PR

**Comment by MichaelBrim** [comment]
I was wrong, it's not fixed - reopening

**Comment by CamStan** [comment]
Will test this again once GitHub Actions are set up

**Pull request closed without merging**
