### PR TITLE
Install unifyfs-stage in bin

### PR DESCRIPTION
**Pull request by rgmiller**
The unifyfs-stage util is expected to be called by users.  As such, it
should be installed in the bin dir rather than libexec.

### Description

Changes a single line in `util/unifyfs-stage/src/Makefile.am` so that `unifyfs-stage` is installed to the `bin` directory.

### Motivation and Context

See issue #709 

### How Has This Been Tested?

Tested by running `make install` (on my Ubuntu workstation) and verifying the location of the installed util.  Also ran `make check` and made sure the change didn't break any existing tests.

### Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x ] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [x ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by CamStan** [comment]
Also not sure why the GitHub Action Checks weren't triggered for this PR. Probably need someone with access to take a look at the settings.

**Comment by rgmiller** [comment]
@CamStan How do I run the tests in the ci directory?  It appears a simple `make check` in my build directory doesn't do it.

**Comment by CamStan** [comment]
> How do I run the tests in the ci directory? It appears a simple `make check` in my build directory doesn't do it.

Correct, they are not tied into `make check` as they are the tests we run through GitLab CI across multiple nodes on the site systems, which can take quite a bit of time.

How to run them in is in the docs. In this case, could just do an individual run of the stage tests in this case.
https://unifyfs.readthedocs.io/en/latest/testing.html#running-individual-tests

That process will look something like:
``` bash
$ # Allocate a node
$ 
$ # spack load dependencies
$ 
$ export UNIFYFS_INSTALL=<unifyfs install location using with this run> 
$
$ cd $UNIFYFS_SOURCE/t/ci
$
$ . ./001-setup.sh
$ . $UNIFYFS_CI_DIR/002-start-server.sh
$ . $UNIFYFS_CI_DIR/800-stage-tests.sh
$ . $UNIFYFS_CI_DIR/990-stop-server.sh
$
$ # If all are successful, it should auto cleanup, otherwise you'll end up with a trash directory with logs for troubleshooting.
```

I do run them regularly on LC systems after commits to `dev`. I haven't personally ran them on ORNL systems in a while, but I would expect them to still be fine (other than there are some currently failing due to other issues). 

---

> And the documentation is just the .rst files in the docs directory, right? The readthedocs.io site is updated from those files, right?

Correct. The readthedocs site will auto update from these after being merged.

**Review by CamStan — APPROVED** [review]
Thanks @rgmiller!

**Comment by adammoody** [comment]
Thanks @rgmiller and @CamStan

**Pull request merged**
