### PR TITLE
0.9.0 transfer api doc

### PR DESCRIPTION
**Pull request by craigsteffen**
An initial example of using the transfer API in the example executable.  
### Motivation and Context

We don't have any documentation on the transfer API up to now.  This is a start of that documentation.  If this is reasonable and acceptable I expect I'll write more. 
### How Has This Been Tested?

It shows up fine on the preview doc window.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the UnifyFS code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by tonyhutter** [comment]
Can you please rebase your changes to get rid of the merge commits?

**Comment by craigsteffen** [comment]
> Can you please rebase your changes to get rid of the merge commits?

I don't understand why there are 6 commits.  0.9.0 was just created within the past few weeks, right?  So how can there be 6 commits going back 2 years when I did a PR against 0.9.0 which is only a few weeks old?   

I want to have this PR against the 0.9.0, so that it shows up in the 0.9.0 documentation, which is the one that shows up on the documentation site by default.  If I did that wrong, I'm sorry.  I realize by default new code changes go against dev, but I tried to not have it do that.  

Feel free to call me at 217-979-2392 if that would help.  I'll probably be at my desk for another half and hour before I start driving this afternoon, and I'll be in my home office all day tomorrow.

Craig

**Comment by MichaelBrim** [comment]
@craigsteffen It's git, you can't change the past, so there's no way to add new documentation to a released (i.e., tagged) version. Just make your changes against dev. Cameron already said he's going to look into pointing the read-the-docs at latest by default.

**Comment by craigsteffen** [comment]
*sigh*.  Ok; I think that means that we'll never ever have documentation
that's in synch with the stable version.

Instead of rebasing, then, I'll just remove the PR completely and re-do it
against a currently dev branch.  That should be simplest, I would think?

**Comment by tonyhutter** [comment]
@craigsteffen unfortunately we need to update the way we do releases in UnifyFS.  Ideally:

1. We'd have a `release` branch.
2. We'd cherry-pick all stable commits into the `release` branch
3. We'd tag the release branch with `v0.X.x` when we want to do a release.

That way you could open a PR against the release branch and it would "just work".  This is how we do ZFS releases and there haven't been any issues.

**Comment by craigsteffen** [comment]
Ok.  I have to get on the road.  I'll do this late tonight or first thing
tomorrow morning.

Thanks for the help everyone.

**Pull request closed without merging**
