### PR TITLE
rename unifyfs_error_e to unifyfs_rc

### PR DESCRIPTION
**Pull request by MichaelBrim**
### Description

This commit also removes all of the UnifyFS error codes that mirrored existing errno values, and converts the places we used those codes to just use the errno names. This works because the error enumerator code was modified a while back to allow for errno values to not conflict with new error codes we define. There is also a new `unifyfs_rc_errno()` method to return a valid errno value from any of the unifyfs_rc values.

This also removes the long dead domain socket code, which enabled removal of a bunch of UNIFYFS_ERROR_SOCK_XXXX codes.

### Motivation and Context

This is the first in a series of PRs to break up my work on the MichaelBrim/client-api branch into more manageable pieces.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by tonyhutter** [comment]
Very nice cleanup!  :+1: :+1: :+1:

**Comment by adammoody** [comment]
Looks great.  Thanks, @MichaelBrim .  There are some conflicts that need to be resolved before we can merge, though.

**Comment by MichaelBrim** [comment]
@adammoody I resolved the conflicts.

**Comment by adammoody** [comment]
Thanks, @MichaelBrim !

**Pull request merged**
