### PR TITLE
Adding simul POSIX test example.

### PR DESCRIPTION
**Pull request by sandrain**
Adding the simul POSIX testing program.

TEST_CHECKPATCH_SKIP_FILES=examples/src/simul.c

### Description
Including the simul POSIX test (https://github.com/LLNL/simul) in examples.

### Motivation and Context
Testing UnifyFS functionality.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

**Comment by adammoody** [comment]
Thanks, @sandrain .  We may run into the problem with mixed licenses, since I see this source is GPL.

**Comment by CamStan** [comment]
> We may run into the problem with mixed licenses, since I see this source is GPL.

How will we know? That's something I'm not up to speed on at all.

**Comment by sandrain** [comment]
@adammoody @CamStan I was thinking that the license could be problematic.

**Comment by tonyhutter** [comment]
I know the two authors of simul.  I'll reach out to them about the licence.  Maybe they'd be ok with re-licensing it?

**Comment by tonyhutter** [comment]
It should be fine to include simul.c.  @IanLee1521 is fine with it, and @morrone said this:
> It sounds like you are just using it as a stand alone compiled test
> application, not trying to link the simul.c code into some other larger
> binary.
> 
> If that is the case, then there should no legal issue with just
> including it in the UnifyFS repository. It is only if you want to link
> the simul.c code into a binary or library with other code that license
> conflicts (the GPL taking precedence, most likely) would be an issue.

**Comment by sandrain** [comment]
@tonyhutter Thank you!

**Comment by adammoody** [comment]
Thanks, @sandrain .

**Pull request merged**
