### PR TITLE
Fix unifyfs_fskv_init() bug

### PR DESCRIPTION
**Pull request by rgmiller**
### Description

If unifyfsd was started without specifying the shared dir, unifyfs_fskv_init() would not actually initialize the K/V store, but it would return success.  This commit adds code to check for that condition and, if the condition is found, return an error and write an appropriate message to the error log.

Note: most of the changes shown in the diff are actually whitespace.  (A bunch of code got indented one level.)  There's only a handful of new lines of code.

### Motivation and Context

Fixes issue #652

### How Has This Been Tested?

Tested on an Unbuntu workstation.  

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [X] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted.

### CODE REVIEW

**Review by MichaelBrim — CHANGES_REQUESTED** [review]
The fix looks good to me, but you should squash/rebase to make it one commit instead of two.

**Comment by rgmiller** [comment]
> The fix looks good to me, but you should squash/rebase to make it one commit instead of two.

Can I modify this PR to do that?  Or should I delete the PR and create a new one?

**Comment by MichaelBrim** [comment]
Do the rebase in your branch, then force push. The PR will automagically pick up the branch change.

**Review by MichaelBrim — APPROVED** [review]

**Comment by adammoody** [comment]
Nice work, @rgmiller and @MichaelBrim .

**Pull request merged**
