### PR TITLE
mentioned -f flag for unifyfsd in config intro

### PR DESCRIPTION
**Pull request by craigsteffen**
Add a paragraph to the intro in the configuration documentation to
specifically call out that the configuration file location for
unifyfsd can be overridden by the -f command-line flag.  This is
mostly for people testing or developing on a system where they
don't have root access and so can't put the configuration file
in the default location in /etc/.

### Motivation and Context

If someone needs to use a configuration file on a system they don't have root access to, this provides that specifically in the introduction to the configuration doc section.  

### How Has This Been Tested?

Just a text change in the doc source.  Tested with the syntax check script.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x ] My code follows the UnifyFS code style requirements.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by MichaelBrim** [comment]
@craigsteffen It may be better to point them to the one installed in `$PREFIX/etc/unifyfs`, rather than the .in file that is used to generate the installed version.

**Comment by craigsteffen** [comment]
Ok.  The extras also contains a file without the .in suffix, and I checked
the two, and they're identical.

That's a good point thought.  Referring to the installed version would
probably be cleaner.  I'll (attempt) to fix that now.

Craig

**Comment by craigsteffen** [comment]
backing out to implement a suggestion of a better way to refer to this from Mike Brim.

**Comment by CamStan** [comment]
@craigsteffen, if you push updated changes to the same branch you made the pull request from, it will automatically update your pull request without needing to close it and open a new one. One of the not-so-obvious features of GitHub.

**Comment by craigsteffen** [comment]
Er...Ok, but I thought we'd been asked to rebase a series of changes down
to one before submitting it as a pull request, especially (as in this case)
the later change essentially fixes the earlier commit and makes it what it
should have been in the first place.

**Comment by CamStan** [comment]
Yup, but a pull request (PR) is based on the branch you want to merge, not the commits. So once a PR is open, you can add more commits to that branch, or rebase them into one, and GitHub will automatically update the PR when you push (or force push in the case of a rebase) to the same remote branch your PR is coming from. That way you don't have to worry about any changes being perfect before opening a PR.

**Comment by craigsteffen** [comment]
Oh.  Ah.

In any case, I've now done an interactive based twice in the past half
hour, so that was useful training.

So I now have what I believe to be the real PR in place, as a single
commit.  Thanks for the update about how that all works.  The fact that
forks and branches are not synonyms in git still makes my brain hurt.

Thanks for the help.  This was a trivial change, and far more of a training
exercise for me than a critical update for the repo, but in that respect it
was quite worthwhile.

Craig

**Pull request closed without merging**
