### PR TITLE
fix for laminate bcast when inode does not exist

### PR DESCRIPTION
**Pull request by MichaelBrim**
### Description

When we laminate a file, the file owner broadcasts its extents and metadata to all other servers. However, there is no guarantee that the inode for the file existed on the other servers before the laminate, as there may not have been client writes to the file on those servers. As a result, the updates to extents and metadata previously failed with ENOENT. This PR fixes that case.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by MichaelBrim** [comment]
This breaks lamination, because you can't add extents after the setting `file_attrs.is_laminated`. I'll update and resubmit.

**Comment by CamStan** [comment]
First attempt was still failing. Grabbing update now.

**Comment by MichaelBrim** [comment]
pushed another update to make checkpatch happy

**Comment by CamStan** [comment]
But no functionality change it the checkpatch push?

This appears to be working now with my initial test (running twice, two nodes with 1ppn). Will run a few more.
One thing that jumped out in the server logs now is this, just before the laminate happens for the second file:
```
# node with write server
2020-12-17T12:22:13 tid=135925 @ unifyfs_invoke_broadcast_truncate() [server/src/unifyfs_group_rpc.c:839] truncate_bcast_forward failed: (ret=2)

# node with read server
2020-12-17T12:22:13 tid=39990 @ truncate_bcast_forward() [server/src/unifyfs_group_rpc.c:701] unifyfs_inode_truncate(gfid=1346058476, size=0) failed - ret=2
```

I'll let you know result my other runs.

**Comment by MichaelBrim** [comment]
That truncate_bcast_forward() error (ENOENT) is weird. Did you enable pre/post truncate in the write client? Still, it could be another place where we need to create the inode before applying the metadata update.

**Comment by CamStan** [comment]
With this fix, data check is now passing on all the producer/consumer cases in which it was previously failing for me.

---
>Did you enable pre/post truncate in the write client?

I double checked and I don't have pre/post truncate enabled in the write client.

When I checked client log, the only truncate I'm seeing is during file creation. The timestamp for the failure matched with the server logs above. 
```
2020-12-17T12:22:13 tid=135920 @ invoke_client_truncate_rpc() [client/src/margo_client.c:521] invoking the truncate rpc function in client
2020-12-17T12:22:13 tid=135920 @ invoke_client_truncate_rpc() [client/src/margo_client.c:534] Got response ret=2
2020-12-17T12:22:13 tid=135920 @ __wrap_open() [client/src/unifyfs-sysio.c:1126] using fds (internal=0, external=16384) for fid 0 file /unifyfs/write-gotcha-2.app
DEBUG: finished create
```

However, "truncate" doesn't appear in the client logs when running my same tests with the current `dev` branch.

I can send the logs if wanted. However, I switched to running two examples back to back in a non-producer/consumer setting (both hosts write and read) and this failure happens on the second run there as well. So might be able to reproduce on your end and it's possibly a different issue this fix uncovered which could be addressed separately.

**Comment by MichaelBrim** [comment]
Leaving this PR as is for now since it is fixing Cameron's test cases. I'll look for the truncate issue and file a separate PR if I find a fix.

**Review by adammoody — APPROVED** [review]
Thanks, @MichaelBrim !

**Pull request merged**
