### PR TITLE
Migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by CamStan**
### Description

Migrate from using Travis CI to GitHub Actions.

Will trigger on all branch pushes as well as pull requests to the dev branch.

Runs checkpatch.

Tests installing dependencies with Spack, building UnifyFS, and running the
unit tests across multiple GCC compiler versions (7, 8, 9, 10, 11).

### Motivation and Context

- More immediate results for build results/errors, style issues, and smoke tests when creating PRs
- Travis CI no longer being used.

### How Has This Been Tested?

Ran and passed in forked repo ([here](https://github.com/CamStan/UnifyFS/actions/runs/1786971889))

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Testing (addition of new tests or update to current tests)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Review by adammoody — APPROVED** [review]
Nice!  Great work!

**Comment by CamStan** [comment]
Looks like one quick change I need to add.

**Comment by adammoody** [comment]
Thanks, @CamStan .  I'll let it sit a day or so before merging in case others want to review.

**Comment by CamStan** [comment]
@adammoody, sounds good! It should be good now.
At some point after being merged I might need you to check the repo's settings on actions and branch protections since I can't view settings (can do this in the next meeting).

**Pull request merged**
