### PR TITLE
client: do not unlink superblock file on unmount

### PR DESCRIPTION
**Pull request by adammoody**
The client was calling shm_unlink during unmount, which deleted the superblock shared memory file so that future clients could not reattach to it.  This has been changed to not shm_unlink that file on the client.  The server now deletes that file during its cleanup logic.

Also, this modifies the client to immediately delete its read request and read reply shared memory files upon returning from the mount_rpc.  The server attaches to those segments during the mount rpc, so it's safe to delete the files at that point.  It also deletes those files in more failures cases for improved cleanup after failure.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by adammoody** [comment]
@clmendes , I think this may fix the unmount bug you found.

**Comment by adammoody** [comment]
Thanks @MichaelBrim .

**Comment by clmendes** [comment]
Yes, this did solve the problem that had been observed when "unmount" was used, and the next app in the same job script was not able to access the contents of the file. After rebuilding UnifyFS today, I can now get the full file exported correctly by sysio-cp-gotcha, after having run "sysio-write-gotcha -u" ! Thanks!

**Comment by adammoody** [comment]
Great.  Thanks for verifying that @clmendes .

**Pull request merged**
