### PR TITLE
Add missing ax_phreads.m4

### PR DESCRIPTION
**Pull request by boehms**
### Description

Commit 6a4f566ba04e0288e5a6a9c263553eb8ff4fef43 adds a call to AX_PTHREADS to [configure.ac](https://github.com/LLNL/UnifyFS/blob/6a4f566ba04e0288e5a6a9c263553eb8ff4fef43/configure.ac#L199).
This adds the corresponding m4 file.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by tonyhutter** [comment]
Many distos already provide `ax_pthreads.m4` as part of their `autoconf-archive` package.  Also this file is GPL'd, which may or may not be an issue.

**Comment by boehms** [comment]
I ran into issues on Summit, and I am not sure if we can assume it will be available on all systems.
And the license for the autotools-archive is not GPL, so we should be fine on that end.

**Comment by tonyhutter** [comment]
@boehms I don't understand.  We're not distributing an `autoconf-archive` package with Unify.  `ax_pthreads.m4` is GPL'd, and that's what we would be distributing.  Again, I don't know if this is actually a problem or not, just wanted to bring it up.

If we're worried about the GPL, one possible alternative would be to try to use ax_pthreads first, and when that doesn't work/exist, have the Makefile fall back to manually passing `-lpthreads`.  My guess is that most Linux machines are going to accept it (hopefully Summit included).

**Comment by boehms** [comment]
Using AX_PTHREAD adds an external dependency, that we can not test for. To make it worse, if the macro is not installed, it fails silently.
You are right about the GPL, it looks like ax_pthread.m4 is GPL (I was looking at the autoconf archhive webpage).

I am not sure how to proceed here.

Do you have an oppinion ion this @MichaelBrim @adammoody @CamStan?

**Comment by tonyhutter** [comment]
> Using AX_PTHREAD adds an external dependency, that we can not test for. 

Can't we use `m4_ifdef([AX_PTHREAD], ...`?

**Comment by boehms** [comment]
I suppose we could. But this would still only fail at configure time, rather than at autogen time. I am not sure what the right solution is. We might be able to check in the autogen.sh script.

**Comment by MichaelBrim** [comment]
My suggestion:
```
m4_ifdef([AX_PTHREAD], [AX_PTHREAD],
  [AC_MSG_ERROR([AX_PTHREAD missing from system. You need to install ax_pthread.m4 from autoconf-archive in the m4/ directory before rerunning configure. Try 'cd m4; wget http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_pthread.m4'])])
```

**Comment by MichaelBrim** [comment]
We could also add an optional step to autogen.sh to download all the autoconf-archive macros we use into `m4/`

**Comment by tonyhutter** [comment]
Or just hardcode `-lpthread` and ignore ax_pthread entirely.  I would be shocked to find a Linux disto that didn't support `-lpthread` out of the box.

**Comment by MichaelBrim** [comment]
@tonyhutter The one real benefit of using AX_PTHREAD is it sets the proper build flags for various compilers.

**Comment by tonyhutter** [comment]
@MichaelBrim we don't use any AX_PTHREAD build flags.  We only use ax_pthread.m4 in a hacky check (that I added, sadly...):
```
configure.ac:200:AX_PTHREAD([],[AC_MSG_ERROR([pthreads are required])])
```
And then we hardcode `-lpthread` in a couple of places:
```
t/Makefile.am:81:	-lpthread -lm -lstdc++ -lrt
server/src/Makefile.am:36:    -lpthread -lm -lstdc++ -lrt
client/src/Makefile.am:42:  -lcrypto -lrt -lpthread
client/unifyfs-config.in:15:POST_LD_FLAGS="$UNIFYFS_LIB_PATH/libunifyfs.a -lcrypto -lm -lrt -lpthread"
```
I would just remove the configure.ac check - at best it's useless and and worst it harmful.  If you had ax_pthread.m4 installed, but not actual pthreads, I think it would pass...

**Comment by MichaelBrim** [comment]
If we're not properly using the flags set by AX_PTHREAD, we should get rid of it.

**Comment by tonyhutter** [comment]
@MichaelBrim agreed.  @boehms can you update your patch to simply get rid of this line and verify it fixes your issue?:
```
configure.ac:200:AX_PTHREAD([],[AC_MSG_ERROR([pthreads are required])])
```

**Comment by MichaelBrim** [comment]
Closing in favor of removing the use of AX_PTHREAD, implemented in PR #457

**Pull request closed without merging**
