### PR TITLE
server: flush extent buffer to server when full

### PR DESCRIPTION
**Pull request by adammoody**
This will flush the file extent index buffer to the server whenever it fills up (resolves https://github.com/LLNL/UnifyFS/issues/387).

Currently, this is using fsync(gfid) for the current file.  That so happens to flush all extents, regardless of gfid.  If fsync is made to adhere to only flushing data for the given file, this needs to be changed to flush all extents in the buffer or otherwise each file should have space to store its own extents.

This uses the unifyfs_gfid_from_fid(fid) function to lookup global file id values everywhere, eliminating get_gfid() and calls to bsearch() to search the file attributes in the shared memory segment (resolves https://github.com/LLNL/UnifyFS/issues/394).

This changes the server to avoid setting file attributes on fsync, and it drops the shared memory segment used to transfer file attributes from the client to the server during fsync.  A while ago, we switched to a mode where file attributes are set by the client via rpc when a file is created.  The shared memory buffer is no longer needed.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commit messages are properly formatted.

### CODE REVIEW

**Comment by MichaelBrim** [comment]
Not really a comment on your changes, but something I noticed while looking at them. There are a lot of places where we assume the pointer returned from `unifyfs_get_meta_from_fid(fid)` is non-NULL, even though it could be NULL in theory if someone passed it a bad fid. Maybe we should change the `return NULL` case in that function to be an assert() to avoid segfaults.

**Comment by adammoody** [comment]
Yeah, adding a assert there is a good idea.

**Comment by adammoody** [comment]
Good point, I'll keep those as int32_t.  Thanks.

**Comment by adammoody** [comment]
Thanks for your review and suggestions, @MichaelBrim .

**Pull request merged**
