### PR TITLE
Refactor staging functions

### PR DESCRIPTION
**Pull request by jenest**
### Description
Refactors common code in staging functions of `unifyfs-rm.c` into a `generic_stage()` function.

### Motivation and Context
Addresses issue #516.

### How Has This Been Tested?
Using tests 0700 and 9300 on Summit. Unfortunately, these tests fail for either `dev` or my own branch. However, @CamStan is not seeing these problems on LLNL systems.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by CamStan** [comment]
Not sure it has anything to do with this, but I recalled that there is one stage test currently set as `test_might_fail`, but I don't recall why this decision was made.
https://github.com/LLNL/UnifyFS/blob/b5d723dd451585e09fe65c69b4297e027ca00334/t/0700-unifyfs-stage-full.t#L60-L62

Essentially, even if this test fails on Travis,  it will show as passing, which is something we should probably adjust in the long run.

**Comment by jenest** [comment]
I would probably agree that this should be adjusted, but I might let someone that has more experience with this code make the call for whether/how that should be done.

**Comment by jenest** [comment]
It might be best to make sure things are working so I can test my changes. Currently, tests 700 and 9300 are failing on Summit, even with the `dev` branch.

@MichaelBrim Thoughts on addressing this?

**Comment by MichaelBrim** [comment]
@jenest I would just open another issue to resolve problems that already exist.

**Comment by jenest** [comment]
Referenced in a comment on issue #523. I will be happy to create a separate issue if needed.

**Review by MichaelBrim — CHANGES_REQUESTED** [review]
Now that we are generating a single c-string representation of the full launch command, it's no longer necessary to keep a separate c-string for `n_nodes`. Could you update the command `snprintf()` to just use the `%zu` format and pass it `resource->n_nodes` as an arg? This change would go in each of the `xxxrun_stage()` functions.

**Review by MichaelBrim — APPROVED** [review]

**Pull request merged**
